### ISSUE TITLE
Setup an AppVeyor continuous integration build

### ISSUE THREAD

**Issue by JuergenGutsch** [JuergenGutsch/LightCore#2]
- [x]  Setup a build script using CAKE
  - build all and run all unit test 
- [x] Integrate it into AppVeyor

**Comment by peterbucher** [comment]
@JuergenGutsch When you starting setup the build, you can also setup to run the unittests on build. Would be great!

**Comment by JuergenGutsch** [comment]
That's for sure :) 
If I say "build", it actually means continuous integration :)
