### ISSUE TITLE
We need to complete the ASP.NET Core integration package

### ISSUE THREAD

**Issue by JuergenGutsch** [JuergenGutsch/LightCore#6]
We need to complete the ASP.NET Core integration package to get it running in ASP.NET Core and .NET Core

- Needs some more time, because it needs a generic and proper way to move the existing service registrations from the ASP.NET Core's IServiceCollection to LightCore
- The current implementation doesn't catch two pretty special service registrations from the IServiceCollection to LightCore, which are the following:
 
`{System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IConfigureOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions]] setups}`

`{System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions]] postConfigures}`

e.g.
```
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Server.Kestrel.Core;

IEnumerable<IConfigureOptions<KestrelServerOptions>>
IEnumerable<IPostConfigureOptions<KestrelServerOptions>>
```

**Comment by peterbucher** [comment]
@JuergenGutsch We can close this issue now?
